services:
  - type: web
    name: reclip
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: BGUTIL_POT_URL
        value: http://bgutil-pot-provider:4416

  - type: pserv
    name: bgutil-pot-provider
    runtime: image
    image:
      url: docker.io/brainicism/bgutil-ytdlp-pot-provider:latest
